swagger: '2.0'
info:
  title: API_NAME
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /dogs:
    get:
      summary: get all dogs
      operationId: dogs
      x-google-backend:
        address: https://REGION-PROJECT_ID.cloudfunctions.net/getDogs
      responses:
        '200':
          description: A successful response
          schema:
            type: string
